<link rel="stylesheet" type="text/css" href="<?=$wwwUrl?>/css/adminOrder.css">

<div>
	<h3>Récapitulatif des commandes</h3>

	<a class="back" href="<?=$requestUrl?>/admin"><i class="fas fa-arrow-circle-left"></i> Retour vers l'admin</a>
	<p>Cliquez sur un numéro de commande pour voir le détail !</p>
	<table class="t-order">
		<thead>
			<th>Numéro de commande</th>
			<th>Prix total</th>
			<th>Date de la commande</th>
		</thead>
		<tbody>
		   
		    
		</tbody>
	</table>
</div>