<link rel="stylesheet" type="text/css" href="<?= $wwwUrl ?>/css/home.css">


<?php if(array_key_exists('user', $_SESSION)) {?>
        <h1>Heureux de te revoir sur Beer4You <?=$_SESSION['user']['firstname']?></h1>
<?php } else {?>
		<h1>Bienvenue sur Beer4you</h1>
<?php } ?>

<p id="home-presentation">Le site de vente de bière le plus côté du marché, ici vous trouverez les meilleures bières, 
de la 86 à la kronembourg. Nous mettons un point d'honneur à vous la facturer chère et à vous livrer tiède.</p>


<img id="homerHome" class="" src="<?= $wwwUrl?>/images/logo/kroHome.jpg"/>


<div class="c-b"></div>