<link rel="stylesheet" type="text/css" href="<?= $wwwUrl ?>/css/detail.css">

<div id="errorPopUp" class="hide popUp">
    <p id="closePopUpError" class="closePopUp">X<p>
    <h4>ça ne peut pas marcher !</h4>
    <p>Si vous ne rentrez pas un chiffre, on ne peut pas compter</p>
    <img src="<?= $wwwUrl ?>/images/logo/ivrogne.jpg">
    <button class="closePopUp">Retour au achat</button>
</div>

<div id="productPopUp" class="hide popUp">
    <p id="closePopUpProduct" class="closePopUp">X<p>
    <h4>Félicitation !</h4>
    <p>Vous avez ajouté <em id="beerNumber"></em> bière(s) à votre panier</p>
    <img src="<?= $wwwUrl ?>/images/logo/ivrogne.jpg">
    <button class="closePopUp">Retour au achat</button>
</div>

<a class="comeBack" href="<?= $requestUrl ?>/products"><i class="fas fa-arrow-circle-left"></i></a>
<div class="beerDetail">
    <!-- je veux les infos du produits ici et aussi un formulaire avec un input pour la quantité et un boutton pour l'achat -->


</div>